#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6207-web 
    bind *:80
    mode http
    balance roundrobin
    server 6207-web-01 54.91.55.243 check
    server 6207-web-02 3.87.173.25	 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
