#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect
# above requirements (this script will be run on the server itself)
# bash script to install nginx web server
#   - Nginx should be listening on port 80
#   - Return page containing "Holberton School" when queried

apt-get update
apt-get install -y nginx

mkdir /var/www/html
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
